coverage:
    status:
        project:
            default:
                target: 95%
                threshold: 1%
        patch:
            default:
                target: 90%
                threshold: 2%

flags:
    javascript:
        carryforward: false
    php:
        carryforward: false

comment:
    layout: "condensed_header, flags, tree"
    behavior: default
    require_changes: false
