name: Upload Coverage
description: Upload coverage reports to Codecov

inputs:
    token:
        description: Codecov token
        required: true
    flags:
        description: Coverage report flags (e.g. php, javascript)
        required: true
    files:
        description: Path to coverage XML file (PHP clover XML)
        required: false
        default: ''
    directory:
        description: Path to coverage directory (JS coverage dir)
        required: false
        default: ''

runs:
    using: composite
    steps:
        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
          with:
              token: ${{ inputs.token }}
              flags: ${{ inputs.flags }}
              files: ${{ inputs.files }}
              directory: ${{ inputs.directory }}
